### ISSUE TITLE
Feature Request - Gas Transaction fee in USD

### ISSUE THREAD

**Issue by bartlanz** [mgarciate/ethgas-ios#15]
on the main screen, and (if possible) on the widget, Could you show what the gas fee translates to in in USD for a transfer?

Gas units (limit) * (Base fee + Tip) = Ammount in GWEI. Then convert to eth so that amount divided by 1000000000 gives you the amount in ETH, Amount of Eth times exchange rate. is the number I think would be helpful.

method pulled from https://ethereum.org/en/developers/docs/gas/

Thank you for adding the persistent notifications option! it is super helpful!

**Comment by mgarciate** [comment]
Hi @bartlanz, in the last version I already created a full screen sheet to show fee details in dollars. Did you notice that? Check the following screenshots:

![IMG_44ED6BD7CBD2-1](https://user-images.githubusercontent.com/7695193/141207173-ca56cf1c-d450-468b-8b81-a3f2cb389ace.jpeg)
![IMG_3D9A07BD9CBA-1](https://user-images.githubusercontent.com/7695193/141207181-4e91f8db-fa51-4a48-b93d-7b429a4b2ba9.jpeg)

**Comment by bartlanz** [comment]
Just updated! That’s awesome! I hope you’re selling the heck out of this app, you’re making a great app!

**Comment by mgarciate** [comment]
> Just updated! That’s awesome! I hope you’re selling the heck out of this app, you’re making a great app!
> […](#)

Well, when several users have bought the application and it is useful for someone, it is enough to maintain it for a long time.
Suggestions of new features are welcome @bartlanz
